### ISSUE TITLE
Project table too wide for mobile

### ISSUE THREAD

**Issue by bkimminich** [OWASP/www-project-mobile-security#13]
![](https://i.imgur.com/r0sMlXf.png)

_Sent from my Pixel 3 XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by commjoen** [comment]
Hmm good point! Can you help me out? Is there a way to separate it based on viewport (e.g. to have a table for large screens and a table for small screens)?

**Comment by bkimminich** [comment]
I simply opted for a two-column table in my case here: https://owasp.org/www-project-juice-shop/#div-ecosystem

I guess if you put the link on the project name, you're rid of the "More Info" column and if you put the leaders names into the first column in braces or whatnot, it should look okay on all screens.

**Comment by commjoen** [comment]
trying 3 columns first... possibly still off, but i remember the fuzz about the leaders not being visible enough...

**Comment by commjoen** [comment]
it would be great if we have media selector classes so we can show a simplified table on mobile ^^.  Then we can easily fix this...

**Comment by commjoen** [comment]
Can you check again @bkimminich please? Is this better?

**Comment by bkimminich** [comment]
![](https://i.imgur.com/G7oadhy.png)
![](https://i.imgur.com/HG893R6.png)

**Comment by commjoen** [comment]
Jeej, good enough for now. Let's close down the issue :)
