### ISSUE TITLE
Mobile Top 10 Security Risks project page is incomplete

### ISSUE THREAD

**Issue by waldenmelinda** [OWASP/www-project-mobile-security#14]
https://owasp.org/www-project-mobile-top-10/

this page used to list the top 10 mobile security risks. it now shows a template page. The content for the subject is no longer there.

**Comment by commjoen** [comment]
Hi @waldenmelinda, the mobile top 10 has its own repo: https://github.com/OWASP/www-project-mobile-top-10 . So i guess a link to https://owasp.org/www-project-mobile-top-10/ needs to be made :). Would you like to file a PR?

**Comment by commjoen** [comment]
Ah sorry, i misread your issue :(.

So basically that has its own repo: https://github.com/OWASP/www-project-mobile-top-10 . Maybe you can best file an issue there? I believe the project leader should be able to migrate the old content to it... Or can I ask you a favor to help in the migration? The data from https://wiki.owasp.org/index.php/OWASP_Mobile_Security_Project#tab=Top_10_Mobile_Risks and https://wiki.owasp.org/index.php/OWASP_Mobile_Top_10 will have to be migrated to that repo... But I don't see me doing that at this point in time... Sorry about that... Well spotted anyway!

**Comment by commjoen** [comment]
@hblankenship do you know who should follow up on this for this repo?

**Comment by JamesHDavenport** [comment]
At the very least a link could be put in to the Web Archive version of the stuff.

**Comment by commjoen** [comment]
See https://github.com/OWASP/www-project-mobile-security/commit/534ace65de64b18e6417a8bc7d38982e5f31c3fb for adding the link. Awaiting review for it.

**Comment by JamesHDavenport** [comment]
Thanks – but you still can’t get the actual list that way, I think.   I believe there should be an explicit link to https://web.archive.org/web/20190113162748/https://www.owasp.org/index.php/Mobile_Top_10_2016-Top_10<https://web.archive.org/web/20190113162748/https:/www.owasp.org/index.php/Mobile_Top_10_2016-Top_10> (or some other date).

**Comment by commjoen** [comment]
Actually, you can navigate to the lists this way ;-), Please have a look at the commit: it will lead you to navigatable lists. I don't think using web.archive.org is a good idea: the OWASP website is about using _up to date_ OWASP resources. Leading to archive.org is not a solution for as far as I can see.

**Comment by commjoen** [comment]
More specifically : "See <a href="https://wiki.owasp.org/index.php/OWASP_Mobile_Security_Project#tab=Top_10_Mobile_Risks">this archive site</a> and <a href="https://wiki.owasp.org/index.php/OWASP_Mobile_Top_10"> this archive site</a>" as part of the commit.

**Comment by commjoen** [comment]
Links to the mobile top 10 are added now and should be visible. @hblankenship how should we move forward now?

**Comment by JamesHDavenport** [comment]
Many thanks for this: my students should be grateful.

**Comment by commjoen** [comment]
You're welcome!

**Comment by WillChilcutt** [comment]
Hi, not sure if anyone here in interested in it, but I made a PR to help get the new page in at least a good start: https://github.com/OWASP/www-project-mobile-top-10/pull/2

I'm totally open to recommendations/feedback/etc. just want to help other people that also landed at the template page. :)

Thanks!

**Comment by WillChilcutt** [comment]
Hi @waldenmelinda I think I hopefully fixed this issue for you. Let me know if you see any additional work. I am currently sending out PR's to update other OWASP projects that point to old Top 10 Mobile links. Thanks!

**Comment by waldenmelinda** [comment]
I did check the URL two days ago and was able to get to the mobile top 10
risks page, so thank you!

**Comment by commjoen** [comment]
Thanks @WillChilcutt ! Closing this as fixed in https://github.com/OWASP/www-project-mobile-top-10/pull/2
