### ISSUE TITLE
Decide on ownership

### ISSUE THREAD

**Issue by commjoen** [OWASP/www-project-mobile-security#8]
@sushi2k , @hblankenship : who should own this space? Because it is not in our scope, but we started with at least porting the living material. How far should we go? Should we migrate 

- https://www.owasp.org/index.php/OWASP_Mobile_Security_Project#tab=Top_10_Mobile_Risks
- https://www.owasp.org/index.php/OWASP_Mobile_Security_Project#tab=Secure_M-Development
- https://www.owasp.org/index.php/OWASP_Mobile_Security_Project#tab=Top_10_Mobile_Controls
- https://www.owasp.org/index.php/OWASP_Mobile_Security_Project#tab=M-Threat_Model_Project

**Comment by sushi2k** [comment]
Let's discuss in our weekly call.

**Comment by commjoen** [comment]
Now in discussion via mail

**Comment by commjoen** [comment]
Decision made in call with @hblankenship after having no new owner found:
- none of the projects listed will be migrated in the current migration plan: these will have to be restarted actively in order to get a new link to them (submitted via a pull request by the owner).
- @hblankenship , @sushi2k , @commjoen will only review merge requests for updating the links till 12-2020 on which we either remove the repo completely or have a new owner?
